### ISSUE TITLE
optional/omitted jobParameters are reloaded from previous jobs

### ISSUE THREAD

**Issue by peter-fe** [codecentric/spring-boot-starter-batch-web#38] opened 2016-09-28 11:10 UTC
When you are using optional job parameters or in the case a mandatory job parameter is simply not provided the missing/omitted parameter gets loaded from the job repository from a former successful job.

In case of restarting a failed job this should be ok, but when dealing with optional parameters or if some mandatory parameters are not provided this can cause some wired results.

Right now I get a list of every parameter used for this job since the 1st run plus the ones I provided for the actual run.

Is this behaviour intended? Is there a way I can assure that only the provided jobParameters are used, like some flag to supress the reload from repository?

Best regards
Peter

**Comment by joshiste** [comment] 2016-09-30 06:36
This is due to the behaviour in the used `RunIdIncrementer` form spring-batch. 
The used JobParametersBuilder constructor copies als parameters from the old instance.
This is not a bug of spring-boot-starter-batch-web

We shipped our own Implementation overcoming this issue:

```java
public class RunIdIncrementer implements JobParametersIncrementer {
	private static String RUN_ID_KEY = "run.id";
	private String key = RUN_ID_KEY;

	public void setKey(String key) {
		this.key = key;
	}

	public JobParameters getNext(JobParameters parameters) {
		JobParameters params = (parameters == null) ? new JobParameters() : parameters;
		long id = params.getLong(key, 0L) + 1;
		return new JobParametersBuilder().addLong(key, id).toJobParameters();
	}
}
```

**Comment by tobiasflohre** [comment] 2016-09-30 07:52
Thanks Johannes :-).
I close this issue.

**Closed by tobiasflohre** 2016-09-30 07:52 UTC

**Comment by peter-fe** [comment] 2016-09-30 17:34
Hi Johannes,

Thank you for the fast response. The snip you provided is the default implementation or the mentioned "own" implementation?

regards 
Peter
